config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  resources :projects do
    resources :rooms do
      resources :items
    end
  end
  # Defines the root path route ("/")
  root "projects#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/item.rb
class Item < ApplicationRecord

  after_create :update_room_cost

  belongs_to :room

  private
    def update_room_cost
      self.room.cost = self.room.cost + self.cost
      self.room.save!
    end
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :rooms
  has_many :snapshots, dependent: :nullify

  before_update :verify_budget
  validates :title, presence: true
  validates :budget, presence: true

  VALID_STATUSES = ['in_progress', 'on_hold', 'complete']

  validates :status, inclusion: { in: VALID_STATUSES }

  private

  def self.record_daily_status
    PrepareProjectSnapshot.perform_now
  end

    def verify_budget
        if self.current_budget > self.budget
            raise Exception.new "Project is over budget!"
        end
    end
end

app/models/room.rb
class Room < ApplicationRecord
  after_update :update_project_cost
  after_create :update_project_cost

  belongs_to :project
  has_many :items
  has_many :snapshots

  validates :name, presence: true
  validates :cost, presence: true

  enum :status, ['in_progress', 'on_hold', 'complete']

  # VALID_STATUSES = ['in_progress', 'on_hold', 'complete']

  # validates :status, inclusion: { in: VALID_STATUSES }

  private

    def self.record_daily_status
      PrepareRoomSnapshot.perform_now
    end

    def update_project_cost
      updated_cost = 0
      self.project.rooms.each do |room| 
        updated_cost += room.cost
      end

      self.project.current_budget = updated_cost
      self.project.save!
    end
end

app/models/snapshot.rb
class Snapshot < ApplicationRecord
  belongs_to :project, optional: true
  belongs_to :room, optional: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

    def show
        @item = Item.find(params[:id])
    end
    
    def new
        @project = Project.find(params[:project_id])
        @room = Room.find(params[:room_id])
        @item = Item.new
    end

    def create
        @project = Project.find(params[:project_id])
        @room = Room.find(params[:room_id])
        updated_params = {
            name: item_params[:name],
            cost: item_params[:cost].to_i,
            room: @room,
        }
        @item = Item.new(updated_params)
    
        if @item.save
          redirect_to project_room_item_path(@project, @room, @item)
        else
          render :new, status: :unprocessable_entity
        end
    end

    private
    def item_params
      params.require(:item).permit(:name, :cost)
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    @projects = Project.all
  end

  def show
    @project = Project.find(params[:id])
  end

  def new
    @project = Project.new
  end

  def create
    updated_params = {
      title: project_params[:title],
      budget: project_params[:budget].to_i,
      start_date: Date.parse(project_params[:start_date])
    }

    @project = Project.new(updated_params)

    if @project.save
      redirect_to @project
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @project = Project.find(params[:id])
  end

  def update
    @project = Project.find(params[:id])

    if @project.update(project_params)
      redirect_to @project
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @project = Project.find(params[:id])
    @project.destroy

    redirect_to root_path, status: :see_other
  end


  private
    def project_params
      params.require(:project).permit(:title, :budget, :start_date)
    end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController

    def index
        @rooms = Project.find(params[:project_id]).rooms
    end

    def show
        @project = Project.find(params[:project_id])
        @room = Room.find(params[:id])
    end
    
    def new
        @project = Project.find(params[:project_id])
        @room = Room.new
    end

    def create
        @project = Project.find(params[:project_id])
        updated_params = {
            name: room_params[:name],
            cost: room_params[:cost].to_i,
            project: @project
        }

        @room = Room.new(updated_params)
    
        if @room.save
          redirect_to project_room_path(@project, @room)
        else
          render :new, status: :unprocessable_entity
        end
    end

    private
    def room_params
      params.require(:room).permit(:name, :cost)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/items/new.html.erb
<h1> New Item for <%= @room.name %> </h1>
<%= form_with(model: @item, url: project_room_items_path(@project.id, @room.id, @item.id)) do |form| %>
    <div>
      <%= form.label :name %><br>
      <%= form.text_field :name %>
      <% @room.errors.full_messages_for(:title).each do |message| %>
          <div><%= message %></div>
      <% end %>
    </div>
  
    <div>
      <%= form.label :cost %><br>
      <%= form.text_area :cost %>
      <% @room.errors.full_messages_for(:body).each do |message| %>
          <div><%= message %></div>
      <% end %>
    </div>

  
    <div>
      <%= form.submit %>
    </div>
  <% end %>

app/views/items/show.html.erb
<h1>This is a page for <%= @item.name %></h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SampleProject</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/projects/_form.html.erb
<%= form_with model: @project do |form| %>
    <div>
      <%= form.label :title %><br>
      <%= form.text_field :title %>
      <% @project.errors.full_messages_for(:title).each do |message| %>
          <div><%= message %></div>
      <% end %>
    </div>
  
    <div>
      <%= form.label :budget %><br>
      <%= form.text_area :budget %>
      <% @project.errors.full_messages_for(:body).each do |message| %>
          <div><%= message %></div>
      <% end %>
    </div>
  
    <div>
      <%= form.label :start_date %><br>
      <%= form.text_field :start_date %>
      <p>date format: yyyy/mm/dd</p>
    </div>
  
    <div>
      <%= form.submit %>
    </div>
  <% end %>

app/views/projects/edit.html.erb
<h1>Edit Project</h1>

<%= render "form", project: @project %>

app/views/projects/index.html.erb
<h1>Projects#index</h1>
<ul>
  <% @projects.each do |project| %>
    <li>
    <a href="<%= project_path(project) %>">
        <%= project.title %>
      </a>
      <%= project.budget %>
      <%= project.start_date %>
      <%= project.current_budget %>
    </li>
  <% end %>

  <%= link_to "New Project", new_project_path %>
</ul>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render "form", project: @project %>

app/views/projects/show.html.erb
<h1><%= @project.title %></h1>

<p>Budget: <%= @project.budget %></p>

<h2>Rooms</h2>
<% @project.rooms.each do |room| %>
    <ul>
        <li>Name: <%= room.name%> Cost: <%=room.cost%> </li>
    </ul>
<% end %>


<ul>
  <li><%= link_to "Add Room", new_project_room_path(@project) %></li>
  <li><%= link_to "Edit", edit_project_path(@project) %></li>
  <li><%= link_to "Destroy", project_path(@project), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %></li>
</ul>

app/views/rooms/index.html.erb
<h1> This is the room index </h1>
<% @rooms.each do |room| %>
    This is a room name: <%= room.name %>
<% end %>

app/views/rooms/new.html.erb
<h1> New Room for <%= @project.title %> </h1>
<%= form_with model: [@project, @project.rooms.build] do |form| %>
    <div>
      <%= form.label :name %><br>
      <%= form.text_field :name %>
      <% @room.errors.full_messages_for(:title).each do |message| %>
          <div><%= message %></div>
      <% end %>
    </div>
  
    <div>
      <%= form.label :cost %><br>
      <%= form.text_area :cost %>
      <% @room.errors.full_messages_for(:body).each do |message| %>
          <div><%= message %></div>
      <% end %>
    </div>

  
    <div>
      <%= form.submit %>
    </div>
  <% end %>

app/views/rooms/show.html.erb
<h1> Info for room: <%= @room.name %></h1>

<li><%= link_to "Add Item", new_project_room_item_path(@project.id, @room.id) %></li>